### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by rigid** [ramcdona/Code-Eli#6]
I'm trying to use the latest master to build OpenVSP and get errors [1] which I (uneducatedly) *guess* origin from Code-Eli changes. I noticed, that tests fail which might hint to this problem.

I'm using eigen 3.3.7 and cpptest 1.1.2

Logs: 
* [cmake output](https://gist.github.com/rigid/c5f8fa5fccccaaeebdf278f4d3607348#file-cmake-shell-session) ([with debug-output](https://gist.github.com/rigid/cb3237d2b3e7566ad7e707751dc653d2#file-cmake-shell-session))
* [make output](https://gist.github.com/rigid/c5f8fa5fccccaaeebdf278f4d3607348#file-build-shell-session) ([verbose](https://gist.github.com/rigid/cb3237d2b3e7566ad7e707751dc653d2#file-build-shell-session))
* [make test output](https://gist.github.com/rigid/c5f8fa5fccccaaeebdf278f4d3607348#file-test-shell-session)

[1] Maybe related but actually an OpenVSP issue: Any analysis in OpenVSP crashes with

`Internal error in finddirection():  Unable to find a
  triangle leading from (0.0108592608872, 0.5) to  (-0.5, 0.5).
  Please report this bug to jrs@cs.berkeley.edu
  Include the message above, your input data set, and the exact
    command line you used to run Triangle.`

**Comment by ramcdona** [comment]
That OpenVSP crash is not rooted in Code-Eli.  Instead, it is a message from the Triangle library.  Unfortunately, these can be really tough to really fix -- but often, a small perturbation to your geometry or its tessellation is enough to 'fix' this sort of problem.
